In [1]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5.5,6.5,7.5,8.5])
x+y

array([ 6.5,  8.5, 10.5, 12.5])

In [2]:
x-y

array([-4.5, -4.5, -4.5, -4.5])

In [3]:
x*y

array([ 5.5, 13. , 22.5, 34. ])

In [4]:
x/y

array([0.18181818, 0.30769231, 0.4       , 0.47058824])

In [6]:
x=np.array([[1,2],[3,4]])
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [7]:
np.power(x,2)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [8]:
x.mean()

2.5

In [9]:
x.sum()

10

In [10]:
x.std()

1.118033988749895

In [11]:
x.max()


4

In [12]:
x.min()

1

In [13]:
np.median(x)

2.5

In [15]:
v=x[1,:]
v.max()

4

In [16]:
w=x[:,0]
w.min()

1